#!/bin/bash


alfred
beyond compare
trello
slack
shadowsocksX
sumlime
jdk

https://draculatheme.com/terminal/
点击打开，并在.bash_profile 追加 export CLICOLOR=1



#idea without jdk   ---- sudo idea by normal user
使用前请将“0.0.0.0 account.jetbrains.com”添加到hosts文件中
安装 plugin: lombok gitignore jrebel + 激活码即可
Shift+Ctrl+Alt+/ --- 选择Registry --- compiler.automake.allow.when.app.running enable
https://my.jrebel.com
setting --- comipile --- Build Project Automatically
restart idea

init repo

#gec ssh
ssh-keygen -t rsa -f /root/.ssh/id_rsa.gce -C "gce"
copy pub to gce ssh key





MAVEN_URL="http://apache.mirror.colo-serv.net/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz"
MAVEN_NAME="apache-maven-3.5.2"


Install_MVN(){
        if [ ! -d "/Users/allen/Desktop/soft/maven" ]; then
            cd ${CurrentDir}
            wget ${MAVEN_URL}
	    mkdir /Users/allen/Desktop/soft/maven && tar xzvf apache-maven*.tar.gz --strip-components 1  -C /Users/allen/Desktop/soft/maven
        fi
}

Install_MVN

添加环境变量

export CLICOLOR=1
alias subl="'/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl'"
export MAVEN_HOME=/Users/allen/Desktop/soft/maven   
export PATH=$MAVEN_HOME/bin:$PATH 


