#!/bin/bash

# 安装 wsl ubuntu https://docs.microsoft.com/en-us/windows/wsl/install-win10
# 安装 docker https://store.docker.com/editions/community/docker-ce-desktop-windows
# setting expose port 2375 http://www.linuxidc.com/Linux/2017-11/148438.htm
# auto.sh 会自动追加变量

# listary xshell 网易邮箱大师 360 有道笔记 chrome  jdk beyond RedisDesktopManager visual studio code 

wsl terminal

# idea
# 使用前请将“0.0.0.0 account.jetbrains.com”添加到hosts文件中
# 安装 plugin: lombok gitignore jrebel + 激活码即可
# Shift+Ctrl+Alt+/ --- 选择Registry --- compiler.automake.allow.when.app.running enable
# https://my.jrebel.com
# setting --- comipile --- Build Project Automatically
# restart idea

# gce ssh
# ssh-keygen -t rsa -f $HOME/.ssh/id_rsa.gce -C "gce"
# copy pub to gce ssh key

虚拟机设置
V8 NAT  192.168.168.0 

TYPE="Ethernet"
PROXY_METHOD="none"
BROWSER_ONLY="no"
BOOTPROTO="static"
IPADDR=192.168.168.192
NETMASK=255.255.255.0
GATEWAY=192.168.168.2
DNS1=192.168.168.2
DEFROUTE="yes"
IPV4_FAILURE_FATAL="no"
IPV6INIT="yes"
IPV6_AUTOCONF="yes"
IPV6_DEFROUTE="yes"
IPV6_FAILURE_FATAL="no"
IPV6_ADDR_GEN_MODE="stable-privacy"
NAME="ens33"
UUID="543a6b46-3144-4e7b-905f-934b4f745fbe"
DEVICE="ens33"
ONBOOT="yes"

