version: "3.4"
services:       
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - /root/start/tools/prom/config/us/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"
        
        
        
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    ports:
      - '3000:3000'
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"
             
  
networks:
  web_server_network:

volumes:
  prometheus_data:
      name: prometheus_data
  grafana_data:
      name: grafana_data
