version: "3.4"
services:    
  mysql:
    image: mysql:5.7.20
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --innodb-buffer-pool-size=1024M --max_connections=2048
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - /home/backup:/home/backup

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 1699:80
    environment:
      - PMA_HOSTS=mysql
      - PMA_VERBOSES=local
    depends_on:
      - mysql
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"
        
  nginx:
    image: ${registry:-docker.io}/ydcode/pack:image-nginx-1.0.0
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1688:1688
    volumes:
      - nginx_wwwroot_data:/home/wwwroot
      - nginx_ssl_data:/etc/letsencrypt
      - nginx_conf_data:/etc/nginx/conf.d
      - nginx_temp_logs:/home/temp/logs
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"    
        
  php:
    image: ${registry:-docker.io}/ydcode/pack:image-php-1.0.0
    container_name: php
    restart: always
    ports:
      - 9000:9000
    volumes:
      - nginx_wwwroot_data:/home/wwwroot
      - nginx_ssl_data:/etc/letsencrypt
      - nginx_conf_data:/etc/nginx/conf.d
      - nginx_temp_logs:/home/temp/logs
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"
      
      
        
networks:
  web_server_network:

volumes:
  nginx_conf_data:
      name: nginx_conf_data
  nginx_wwwroot_data:
    name: nginx_wwwroot_data
  nginx_ssl_data:
    name: nginx_ssl_data
  nginx_temp_logs:
    name: nginx_temp_logs
  temp_data:
    name: temp_data
