version: "3.4"
services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    container_name: rabbitmq
    restart: always
    ports:
      - 5671:5671
      - 5672:5672
      - 4369:4369
      - 25672:25672
      - 15671:15671
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"


  rocksdb-server:
    image: ${registry:-docker.io}/ydcode/pack:rocksdb-server-1.0.0
    container_name: rocksdb-server
    restart: always
    ports:
      - 6565:6565
    volumes:
      - rocksdb_data:/home/data/rocksdb
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"
        
        
  mysql:
    image: mysql:5.7.20
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - /home/backup:/home/backup

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: on-failure
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 1699:80
    restart: on-failure
    environment:
      - PMA_HOSTS=mysql
      - PMA_VERBOSES=local
    depends_on:
      - mysql
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"
        
networks:
  web_server_network:

volumes:
  mysql_data:
    name: mysql_data
  rocksdb_data:
    name: rocksdb_data
  rabbitmq_data:
    name: rabbitmq_data
