version: "3.4"
services:       
  nginx:
    image: ${registry:-docker.io}/ydcode/pack:image-nginx-1.0.0
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1688:1688
    volumes:
      - nginx_wwwroot_data:/home/wwwroot
      - nginx_ssl_data:/etc/letsencrypt
      - nginx_conf_data:/etc/nginx/conf.d
      - nginx_temp_logs:/home/temp/logs
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"
  
  useragent:
    image: ${registry:-docker.io}/ydcode/pack:image-user-agent-1.0.0
    container_name: useragent
    ports:
      - 8099:8099
    restart: always
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"
        
  web-rtb-server:
    image: ${registry:-docker.io}/ydcode/pack:web-rtb-server-dev-1.0.0
    container_name: web-rtb-server
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
      - SSL_EMAIL=${SSL_EMAIL}
      - USER_AGENT_HOST=${USER_AGENT_HOST}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - AWS_ACCESS_KEY_MASTER=${AWS_ACCESS_KEY_MASTER}
      - AWS_SECRET_KEY_MASTER=${AWS_SECRET_KEY_MASTER}
      - SERVER_NAME=${SERVER_NAME}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - temp_data:/home/temp
      - nginx_wwwroot_data:/home/wwwroot
      - nginx_ssl_data:/etc/letsencrypt
      - nginx_conf_data:/etc/nginx/conf.d

      - /root/.ssh:/root/.ssh # dev
      - /root/boot:/root/boot # dev
      - /root/.m2:/root/.m2 #dev
    restart: always
    depends_on:
      - nginx
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"
        
      
      
networks:
  web_server_network:

volumes:
  nginx_conf_data:
      name: nginx_conf_data
  nginx_wwwroot_data:
    name: nginx_wwwroot_data
  nginx_ssl_data:
    name: nginx_ssl_data
  nginx_temp_logs:
    name: nginx_temp_logs
  temp_data:
    name: temp_data
  ttl3db_data:
    name: ttl3db_data
