version: "3.4"
services:       
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prom_data:/etc/prometheus
      - /root/prom/:/root/prom/
    command:
      - '--config.file=/root/prom/prometheus.yml'
      
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"
        
        
        
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    ports:
      - '3000:3000'
    networks:
      - web_server_network
    logging:
      options:
        max-size: "200m"
             
  
networks:
  web_server_network:

volumes:
  prom_data:
      name: prom_data
  grafana_data:
      name: grafana_data
